### ISSUE TITLE
Example GraphQL server dead

### ISSUE THREAD

**Issue by benjamin-rood** [hasura/schema-stitching-examples#3]
The primary GraphQL endpoint used in the examples <s>is broken:</s>
`https://bazookaand.herokuapp.com/v1alhpa1/graphql` <s>ENDPOINT DEAD</s>
<s>Returns Heroku's standard Application Error response.</s>

Edit: Actually it's just a typo in a code block in the blog article `v1alhpa1` → `v1alpha1` = 👌

**Comment by michaelhayman** [comment]
`https://bazookaand.herokuapp.com/v1alpha1/graphql` doesn't work now either

`{"path":"$","error":"resource does not exist","code":"not-found"}`

**Comment by wawhal** [comment]
Folks. It is a Heroku app that sleeps if not queried for more than 30 mins. Please try it again and it should work.
